"""empty message

Revision ID: 07aef1c53684
Revises: 57038d70256c
Create Date: 2022-09-27 18:19:48.043925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07aef1c53684'
down_revision = '57038d70256c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'posts', ['id'])
    op.drop_constraint('users_user_email_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_user_email_key', 'users', ['user_email'])
    op.drop_constraint(None, 'posts', type_='unique')
    # ### end Alembic commands ###
